---
- name: Find Example
  hosts: all
  tasks:
   - name : Find files older than 5 days
     find:
       paths: /var/log
       patterns: '*.log'
       age: 5d
       age_stamp: mtime
     register: output

   - debug: var=item.path
     with_items: "{{ output.files }}"
