---
#- import_playbook: req.yml
- name: Installing Ansible collections
  hosts: Linux
  gather_facts: flase
  become: yes
  tasks:
    - name: Installing collection
      command: ansible-galaxy collection install community.windows


- name: Run ipconfig on Windows Server
  hosts: win
  tasks:
    - name: Run ipconfig /all
      ansible.windows.win_command: ipconfig /all
      register: ipconfig_output
    - debug:
        var: ipconfig_output.stdout

- name: Execute Windows Commands
  hosts: win
  tasks:
    - name: List the services
      ansible.windows.win_command: net start
      register: services
      ignore_errors: yes

    - debug:
        var: services.stdout_lines


    - name: Get system information using systeminfo.exe
      ansible.windows.win_command: systeminfo.exe
      register: sysinfo

    - debug:
        var: sysinfo.stdout_lines
